Add `dns_nameserver` option for mx checking
micke/valid_email2 pull request #230
Opened 2024-01-22 11:44 UTC by timkrins

Adds an option for easily customising the DNS resolver that is used for checking A and MX records.
If no option is given, it will use all current defaults.

2024-01-31 22:06 UTC, micke requested changes
Thanks! I just have some feedback!

2024-01-31 22:41 UTC, timkrins commented on README.md
> -It is a good idea to stub out that validation in your test environment.
Indeed it was my editor. Will fix up!

2024-01-31 22:42 UTC, timkrins commented on lib/valid_email2/address.rb
> +      end
I like it

2024-02-01 07:28 UTC, micke commented
@timkrins great! Seems like you have some failing tests still!

2024-02-01 12:39 UTC, timkrins commented
Ensuring the timeout test fails is an interesting one - the DNS response was too quick in CI to fail the test, but passed locally. My current solution to fail the test seems to be a bit 'hacky'. 
As long as the DNS server doesn't respond in less than 2.2250738585072014e-308 seconds (`Float::MIN`), and `resolv` respects a float value, should work (the `timeout` value is validated by `resolv` and must be positive).
The only other way to emulate a timeout might be to start a socket on a thread that does not reply (this is how it is done in the `resolv` lib tests), but this is quite a deviation from the simpleness of the current tests.

2024-02-04 21:00 UTC, micke approved these changes

2024-02-04 21:01 UTC, merged

2024-02-04 22:33 UTC, micke commented
I've pushed 5.2.0 to rubygems. Thanks!